### ISSUE TITLE
make wt 2.2 compatible

### ISSUE THREAD

**Issue by arbor95** [garraflavatra/webtrees-media-folder-import#3]
Call to undefined function Garraflavatra\Webtrees\Module\MediaFolderImportModule\app() …/modules_v4/media-folder-import/MediaFolderImportModule.php:140
#0 …/modules_v4/media-folder-import/MediaFolderImportModule.php(164): Garraflavatra\Webtrees\Module\MediaFolderImportModule\MediaFolderImportModule->getTemplateData()

and others containing app(

**Comment by 0ldM4cM4n** [comment]
I just downloaded this module to use in Webtrees 2.2.6, and to my disappointment, I am getting a similar error as user "arbor95". Please, please fix this. It is ridiculous that when we start a new family tree, we have to browse for media files one at a time. It is tedious and a waste of our time. So this module is REALLY needed! Thank you so much. The error I get is the following, followed by many lines of text:

Call to undefined function Garraflavatra\Webtrees\Module\MediaFolderImportModule\app() …/modules_v4/webtrees-media-folder-import/MediaFolderImportModule.php:140
#0 …/modules_v4/webtrees-media-folder-import/MediaFolderImportModule.php(164): Garraflavatra\Webtrees\Module\MediaFolderImportModule\MediaFolderImportModule->getTemplateData(Object(Nyholm\Psr7\ServerRequest))

**Comment by garraflavatra** [comment]
Hi @arbor95 and @0ldM4cM4n, thanks for reporting the issue! Honestly I haven't been using webtrees since a long time; I'm sorry for having you wait so long. Thanks to @Jefferson49's contribution this should be fixed now, I'll release a new version. Please let me know if it works!

**Comment by 0ldM4cM4n** [comment]
Thank you for your quick response. I didn't really expect to hear from you since you haven't touched this module in three years. You should know that Jefferson also shared a fixed version on the Webtrees forum website, and I can confirm that it is working properly.

If you are interested in another few simple projects, allow me to offer them:

1. A simple mod which will change "My page" on the user's page to something like "This page belongs to:", and then I guess it would be followed by the 'user_id' variable, or whatever is needed to make it work. I am not a coder. You could make that text string editable by the site administrator only. Maybe it can have a light beveled frame around it, using a CSS radius of say 5 to 12.

2. A simple mod that will add a framed announcement or text field  to each user's home page where the site admin can post a message which he wants to remain static, unless he chooses to change it. This would not be a part of the messages module. It would be separate from that.

The text would not be editable by any user other than the site admin. My reason for wanting this mode, is because I want to post an announcement in which I request that my users do NOT share my site's URL with anyone, due to the fact that it contains very personal family data which should only be viewed by family members. Some family members are very sensitive about this.

3. A simple mod to add a png or jpg header image to the top of the site, at least on the home page, if not elsewhere.
